language: c

addons:
  apt:
    packages:
      - libasound2:i386
      - libcairo2:i386
      - libz1:i386
      - libbz2-1.0:i386
      - libssl1.0.0:i386
      - libfreetype6:i386

install: 
  - ./scripts/download.sh
  - ./scripts/install-packages.sh
  - ./scripts/disable-deprecation-warning.sh 

script:
  - ./pharo shiftClassInstaller.image test --no-xterm --fail-on-failure "Shift-ClassBuilder-Tests" "Shift-ClassInstaller-Tests" "Shift-Changes-Tests" "Shift-Changes-Ficus-Tests" "Slot-Tests"

