SystemOrganization addCategory: #AtomicClassInstaller!
SystemOrganization addCategory: 'AtomicClassInstaller-AtomicPatch'!
SystemOrganization addCategory: 'AtomicClassInstaller-AtomicPatchOperations'!
SystemOrganization addCategory: 'AtomicClassInstaller-Loader'!
SystemOrganization addCategory: 'AtomicClassInstaller-Migrators'!
SystemOrganization addCategory: 'AtomicClassInstaller-Monticello'!
SystemOrganization addCategory: 'AtomicClassInstaller-Operations'!
SystemOrganization addCategory: 'AtomicClassInstaller-Process'!
