SystemOrganization addCategory: #AtomicClassInstaller!
SystemOrganization addCategory: 'AtomicClassInstaller-AtomicPatch'!
SystemOrganization addCategory: 'AtomicClassInstaller-AtomicPatchOperations'!
SystemOrganization addCategory: 'AtomicClassInstaller-Contexts'!
SystemOrganization addCategory: 'AtomicClassInstaller-Metacello'!
SystemOrganization addCategory: 'AtomicClassInstaller-Monticello'!
SystemOrganization addCategory: 'AtomicClassInstaller-Operations'!
SystemOrganization addCategory: 'AtomicClassInstaller-Process'!
